param([string]$Root = (Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference = 'Stop'

$states = @{
  'Alabama'='AL';'Alaska'='AK';'Arizona'='AZ';'Arkansas'='AR';'California'='CA';'Colorado'='CO';'Connecticut'='CT';'Delaware'='DE';
  'District of Columbia'='DC';'Florida'='FL';'Georgia'='GA';'Hawaii'='HI';'Idaho'='ID';'Illinois'='IL';'Indiana'='IN';'Iowa'='IA';
  'Kansas'='KS';'Kentucky'='KY';'Louisiana'='LA';'Maine'='ME';'Maryland'='MD';'Massachusetts'='MA';'Michigan'='MI';'Minnesota'='MN';
  'Mississippi'='MS';'Missouri'='MO';'Montana'='MT';'Nebraska'='NE';'Nevada'='NV';'New Hampshire'='NH';'New Jersey'='NJ';'New Mexico'='NM';
  'New York'='NY';'North Carolina'='NC';'North Dakota'='ND';'Ohio'='OH';'Oklahoma'='OK';'Oregon'='OR';'Pennsylvania'='PA';
  'Rhode Island'='RI';'South Carolina'='SC';'South Dakota'='SD';'Tennessee'='TN';'Texas'='TX';'Utah'='UT';'Vermont'='VT';
  'Virginia'='VA';'Washington'='WA';'West Virginia'='WV';'Wisconsin'='WI';'Wyoming'='WY'
}

function Clean([string]$value) {
  $value = [regex]::Replace($value, '<sup[^>]*>.*?</sup>', '', 'Singleline')
  $value = [regex]::Replace($value, '<style[^>]*>.*?</style>', '', 'Singleline')
  $value = [regex]::Replace($value, '<[^>]+>', ' ')
  $value = [Net.WebUtility]::HtmlDecode($value)
  # Windows PowerShell 5 may decode UTF-8 as Windows-1252. Reassemble the
  # original bytes, then normalize smart punctuation for stable team IDs.
  $bytes = [Text.Encoding]::GetEncoding(1252).GetBytes($value)
  $value = [Text.Encoding]::UTF8.GetString($bytes)
  $value = [regex]::Replace($value, '[\u2013\u2014]', '-')
  $value = [regex]::Replace($value, '\u2019', "'")
  return [regex]::Replace($value, '\s+', ' ').Trim()
}
function Cells($row) {
  $out = @()
  foreach ($cell in [regex]::Matches($row, '<t[dh][^>]*>(.*?)</t[dh]>', 'Singleline')) { $out += Clean $cell.Groups[1].Value }
  return ,$out
}
function Capacity([string]$value) {
  $digits = $value -replace '[^0-9]', ''
  if ($digits) { return [int]$digits }
  return 0
}
function TableRows([string]$url, [int]$index) {
  $html = (Invoke-WebRequest -UseBasicParsing $url).Content
  $table = [regex]::Matches($html, '<table[^>]*class="[^"]*wikitable[^"]*"[^>]*>(.*?)</table>', 'Singleline')[$index]
  return [regex]::Matches($table.Groups[1].Value, '<tr[^>]*>(.*?)</tr>', 'Singleline') | Select-Object -Skip 1
}
function StateCode([string]$name) { if ($states.ContainsKey($name)) { return $states[$name] }; return $name }
function SaveData([string]$division, $records) {
  $json = ConvertTo-Json @($records) -Compress -Depth 4
  $content = "/* Generated by scripts/sync-lower-divisions.ps1; affiliations current to the source snapshot. */`nwindow.LowerDivisionData.register('$division',$json);`n"
  $path = Join-Path $Root "js/data/teams-$division.js"
  [IO.File]::WriteAllText($path, $content, (New-Object Text.UTF8Encoding($false)))
  Write-Host "$division`: $($records.Count) programs"
}

$fcs = @()
foreach ($row in TableRows 'https://en.wikipedia.org/wiki/List_of_NCAA_Division_I_FCS_football_programs' 0) {
  $c = Cells $row.Groups[1].Value; if ($c.Count -lt 8) { continue }
  $fcs += ,@($c[0],$c[1],$c[3],(StateCode $c[4]),$c[7],'',0)
}
SaveData 'fcs' $fcs

$d2 = @()
foreach ($row in TableRows 'https://en.wikipedia.org/wiki/List_of_NCAA_Division_II_football_programs' 0) {
  $c = Cells $row.Groups[1].Value; if ($c.Count -lt 8) { continue }
  $d2 += ,@($c[1],$c[2],$c[3],(StateCode $c[4]),$c[6],$c[7],(Capacity $c[8]))
}
SaveData 'd2' $d2

$d3 = @()
foreach ($row in TableRows 'https://en.wikipedia.org/wiki/List_of_NCAA_Division_III_football_programs' 1) {
  $c = Cells $row.Groups[1].Value; if ($c.Count -lt 6) { continue }
  $d3 += ,@($c[0],$c[1],$c[2],(StateCode $c[3]),$c[5],'',0)
}
SaveData 'd3' $d3
